// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from http.djinni

package net.kullo.libkullo.http;

import android.support.annotation.NonNull;
import android.support.annotation.Nullable;

public abstract class HttpClient {
    /**
     * Synchronously send the given request.
     * Not thread-safe! Use a separate HttpClient instance per thread.
     *
     * * timeout in milliseconds or 0 for no timeout
     * * requestListener must be non-null if method is PATCH, POST or PUT
     * * responseListener may be null
     */
    @NonNull
    public abstract Response sendRequest(@NonNull Request request, int timeoutMs, @Nullable RequestListener requestListener, @Nullable ResponseListener responseListener);
}
