// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from http.djinni

package net.kullo.libkullo.http;

import android.support.annotation.NonNull;
import android.support.annotation.Nullable;

public final class HttpHeader {


    /*package*/ final String key;

    /*package*/ final String value;

    public HttpHeader(
            @NonNull String key,
            @NonNull String value) {
        this.key = key;
        this.value = value;
    }

    @NonNull
    public String getKey() {
        return key;
    }

    @NonNull
    public String getValue() {
        return value;
    }

    @Override
    public String toString() {
        return "HttpHeader{" +
                "key=" + key +
                "," + "value=" + value +
        "}";
    }

}
