// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from http.djinni

package net.kullo.libkullo.http;

import android.support.annotation.NonNull;
import android.support.annotation.Nullable;

public enum HttpMethod {
    GET,
    POST,
    PUT,
    PATCH,
    DELETE,
    ;
}
