// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from http.djinni

package net.kullo.libkullo.http;

import android.support.annotation.NonNull;
import android.support.annotation.Nullable;
import java.util.ArrayList;

public final class Request {


    /*package*/ final HttpMethod method;

    /*package*/ final String url;

    /*package*/ final ArrayList<HttpHeader> headers;

    public Request(
            @NonNull HttpMethod method,
            @NonNull String url,
            @NonNull ArrayList<HttpHeader> headers) {
        this.method = method;
        this.url = url;
        this.headers = headers;
    }

    @NonNull
    public HttpMethod getMethod() {
        return method;
    }

    @NonNull
    public String getUrl() {
        return url;
    }

    @NonNull
    public ArrayList<HttpHeader> getHeaders() {
        return headers;
    }

    @Override
    public String toString() {
        return "Request{" +
                "method=" + method +
                "," + "url=" + url +
                "," + "headers=" + headers +
        "}";
    }

}
