// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from http.djinni

package net.kullo.libkullo.http;

public enum ResponseError {
    CANCELED,
    TIMEOUT,
    NETWORKERROR,
    ;
}
