// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from http.djinni

package net.kullo.libkullo.http;

import android.support.annotation.NonNull;
import android.support.annotation.Nullable;

/**
 * Encapsulates the progress of a transfer, measured in bytes.
 * Defaults to 0 if unknown.
 */
public final class TransferProgress {


    /*package*/ final long uploadTransferred;

    /*package*/ final long uploadTotal;

    /*package*/ final long downloadTransferred;

    /*package*/ final long downloadTotal;

    public TransferProgress(
            long uploadTransferred,
            long uploadTotal,
            long downloadTransferred,
            long downloadTotal) {
        this.uploadTransferred = uploadTransferred;
        this.uploadTotal = uploadTotal;
        this.downloadTransferred = downloadTransferred;
        this.downloadTotal = downloadTotal;
    }

    public long getUploadTransferred() {
        return uploadTransferred;
    }

    public long getUploadTotal() {
        return uploadTotal;
    }

    public long getDownloadTransferred() {
        return downloadTransferred;
    }

    public long getDownloadTotal() {
        return downloadTotal;
    }

    @Override
    public String toString() {
        return "TransferProgress{" +
                "uploadTransferred=" + uploadTransferred +
                "," + "uploadTotal=" + uploadTotal +
                "," + "downloadTransferred=" + downloadTransferred +
                "," + "downloadTotal=" + downloadTotal +
        "}";
    }

}
