// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from http.djinni

package net.kullo.libkullo.http;

public final class HttpHeader {


    /*package*/ final String key;

    /*package*/ final String value;

    public HttpHeader(
            String key,
            String value) {
        this.key = key;
        this.value = value;
    }

    public String getKey() {
        return key;
    }

    public String getValue() {
        return value;
    }
}
