// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from http.djinni

package net.kullo.libkullo.http;

import java.util.HashMap;

public abstract class HttpClientFactory {
    public abstract HttpClient createHttpClient();

    /** Returns pairs of <library name, version number> for the libraries used. */
    public abstract HashMap<String, String> versions();
}
