// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from http.djinni

package net.kullo.libkullo.http;

import java.util.concurrent.atomic.AtomicBoolean;

public abstract class ResponseListener {
    /**
     * Returns the progress made on upload and download, measured in bytes. The
     * request can be canceled by returning the appropriate code.
     */
    public abstract ProgressResult progress(long uploadTransferred, long uploadTotal, long downloadTransferred, long downloadTotal);

    public abstract void dataReceived(byte[] data);

    private static final class CppProxy extends ResponseListener
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
        }

        private native void nativeDestroy(long nativeRef);
        public void destroy()
        {
            boolean destroyed = this.destroyed.getAndSet(true);
            if (!destroyed) nativeDestroy(this.nativeRef);
        }
        protected void finalize() throws java.lang.Throwable
        {
            destroy();
            super.finalize();
        }

        @Override
        public ProgressResult progress(long uploadTransferred, long uploadTotal, long downloadTransferred, long downloadTotal)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_progress(this.nativeRef, uploadTransferred, uploadTotal, downloadTransferred, downloadTotal);
        }
        private native ProgressResult native_progress(long _nativeRef, long uploadTransferred, long uploadTotal, long downloadTransferred, long downloadTotal);

        @Override
        public void dataReceived(byte[] data)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_dataReceived(this.nativeRef, data);
        }
        private native void native_dataReceived(long _nativeRef, byte[] data);
    }
}
