// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

package net.kullo.libkullo.api;

/** Information about a Kullo account */
public final class AccountInfo {


    /*package*/ final String settingsUrl;

    public AccountInfo(
            String settingsUrl) {
        this.settingsUrl = settingsUrl;
    }

    /**
     * URL to web interface where account settings (notifications, ...) can be
     * configured
     */
    public String getSettingsUrl() {
        return settingsUrl;
    }
}
