// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

package net.kullo.libkullo.api;

/** Listener used in Client.checkCredentialsAsync() */
public abstract class ClientCheckCredentialsListener {
    public abstract void finished(Address address, MasterKey masterKey, boolean valid);

    public abstract void error(Address address, NetworkError error);
}
