// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from client.djinni

package net.kullo.libkullo.api;

/** Listener used in Client.createSessionAsync() */
public abstract class ClientCreateSessionListener {
    public abstract void migrationStarted(Address address);

    public abstract void finished(Session session);

    public abstract void error(Address address, LocalError error);
}
