// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from messages.djinni

package net.kullo.libkullo.api;

public enum DeliveryState {
    UNSENT,
    DELIVERED,
    FAILED,
    ;
}
