// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

package net.kullo.libkullo.api;

public enum LocalError {
    /** Couldn't read or write to file */
    FILESYSTEM,
    /** Any other error */
    UNKNOWN,
    ;
}
