// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

package net.kullo.libkullo.api;

/** Listener used in Registry.setLogListener() */
public abstract class LogListener {
    /** Called whenever libkullo produces a log message. */
    public abstract void writeLogMessage(String file, int line, String function, LogType type, String message, String thread, String stacktrace);
}
