// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

package net.kullo.libkullo.api;

public enum LogType {
    NONE,
    DEBUG,
    INFO,
    WARNING,
    ERROR,
    FATAL,
    ;
}
