// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from push.djinni

package net.kullo.libkullo.api;

public enum PushTokenEnvironment {
    /** GCM: when run on Android */
    ANDROID,
    /** GCM: when run on iOS */
    IOS,
    /** APNS: when aps-environment=development */
    DEVELOPMENT,
    /** APNS: when aps-environment=production */
    PRODUCTION,
    ;
}
