// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from push.djinni

package net.kullo.libkullo.api;

public enum PushTokenType {
    /** Google Cloud Messaging */
    GCM,
    /** Apple Push Notification Service */
    APNS,
    ;
}
