// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

package net.kullo.libkullo.api;

/** Listener used in Registration.registerAccountAsync() */
public abstract class RegistrationRegisterAccountListener {
    public abstract void challengeNeeded(Address address, Challenge challenge);

    public abstract void addressNotAvailable(Address address, AddressNotAvailableReason reason);

    public abstract void finished(Address address, MasterKey masterKey);

    public abstract void error(Address address, NetworkError error);
}
