// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from registration.djinni

package net.kullo.libkullo.api;

import java.util.concurrent.atomic.AtomicBoolean;

/** Can be obtained through Client.generateKeysAsync(). */
public abstract class Registration {
    /**
     * Register a new account.
     *
     * Set challenge to the value passed to
     * RegistrationRegisterAccountListener::challengeNeeded if you recently sent
     * a registration request for the same address that failed because of a
     * missing or wrong challenge answer. Otherwise, just pass null.
     *
     * If no challenge is needed, set challengeAnswer to ""
     */
    public abstract AsyncTask registerAccountAsync(Address address, Challenge challenge, String challengeAnswer, RegistrationRegisterAccountListener listener);

    private static final class CppProxy extends Registration
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
        }

        private native void nativeDestroy(long nativeRef);
        public void destroy()
        {
            boolean destroyed = this.destroyed.getAndSet(true);
            if (!destroyed) nativeDestroy(this.nativeRef);
        }
        protected void finalize() throws java.lang.Throwable
        {
            destroy();
            super.finalize();
        }

        @Override
        public AsyncTask registerAccountAsync(Address address, Challenge challenge, String challengeAnswer, RegistrationRegisterAccountListener listener)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_registerAccountAsync(this.nativeRef, address, challenge, challengeAnswer, listener);
        }
        private native AsyncTask native_registerAccountAsync(long _nativeRef, Address address, Challenge challenge, String challengeAnswer, RegistrationRegisterAccountListener listener);
    }
}
