// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

package net.kullo.libkullo.api;

/** Listener used in Client.createSessionAsync() */
public abstract class SessionListener {
    /** event must be passed to Session.notify() from UI thread */
    public abstract void internalEvent(InternalEvent event);
}
