// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

package net.kullo.libkullo.api;

/** Listener used in Session.accountInfoAsync() */
public abstract class SessionAccountInfoListener {
    public abstract void finished(AccountInfo accountInfo);

    public abstract void error(NetworkError error);
}
