// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

package net.kullo.libkullo.api;

public final class SyncProgress {


    /*package*/ final long countLeft;

    /*package*/ final long countProcessed;

    /*package*/ final long countTotal;

    /*package*/ final long countNew;

    /*package*/ final long countNewUnread;

    /*package*/ final long countModified;

    /*package*/ final long countDeleted;

    /*package*/ final long runTimeMs;

    public SyncProgress(
            long countLeft,
            long countProcessed,
            long countTotal,
            long countNew,
            long countNewUnread,
            long countModified,
            long countDeleted,
            long runTimeMs) {
        this.countLeft = countLeft;
        this.countProcessed = countProcessed;
        this.countTotal = countTotal;
        this.countNew = countNew;
        this.countNewUnread = countNewUnread;
        this.countModified = countModified;
        this.countDeleted = countDeleted;
        this.runTimeMs = runTimeMs;
    }

    /** stats about messages */
    public long getCountLeft() {
        return countLeft;
    }

    public long getCountProcessed() {
        return countProcessed;
    }

    public long getCountTotal() {
        return countTotal;
    }

    public long getCountNew() {
        return countNew;
    }

    public long getCountNewUnread() {
        return countNewUnread;
    }

    public long getCountModified() {
        return countModified;
    }

    public long getCountDeleted() {
        return countDeleted;
    }

    /** Run time of the current sync in milliseconds */
    public long getRunTimeMs() {
        return runTimeMs;
    }
}
