// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from syncer.djinni

package net.kullo.libkullo.api;

public enum SyncMode {
    /** Do the minimal work required to send all unsent prepared drafts */
    SENDONLY,
    /** Sync everything, but don't download attachments */
    WITHOUTATTACHMENTS,
    /** Sync everything, including attachments */
    EVERYTHING,
    ;
}
