// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

package net.kullo.libkullo.api;

/** Listener used in Syncer.runAsync() */
public abstract class SyncerRunListener {
    public abstract void draftAttachmentsTooBig(long convId);

    public abstract void finished();

    public abstract void error(NetworkError error);
}
