// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from registration.djinni

package net.kullo.libkullo.api;

public enum AddressNotAvailableReason {
    BLOCKED,
    EXISTS,
    ;
}
