// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from registration.djinni

package net.kullo.libkullo.api;

import android.support.annotation.NonNull;
import android.support.annotation.Nullable;

public enum AddressNotAvailableReason {
    BLOCKED,
    EXISTS,
    ;
}
