// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from address.djinni

package net.kullo.libkullo.api;

import android.support.annotation.NonNull;
import android.support.annotation.Nullable;

/** Represents a Kullo address */
public class AddressBase {


    /*package*/ final String localPart;

    /*package*/ final String domainPart;

    public AddressBase(
            @NonNull String localPart,
            @NonNull String domainPart) {
        this.localPart = localPart;
        this.domainPart = domainPart;
    }

    /** Constructor must ensure this is normalized */
    @NonNull
    public String getLocalPart() {
        return localPart;
    }

    /** Constructor must ensure this is normalized */
    @NonNull
    public String getDomainPart() {
        return domainPart;
    }

    @Override
    public String toString() {
        return "AddressBase{" +
                "localPart=" + localPart +
                "," + "domainPart=" + domainPart +
        "}";
    }

}
