// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from syncer.djinni

package net.kullo.libkullo.api;

import android.support.annotation.NonNull;
import android.support.annotation.Nullable;

/** A block of attachments from a single message */
public final class AttachmentsBlockDownloadProgress {


    /*package*/ final long downloadedBytes;

    /*package*/ final long totalBytes;

    public AttachmentsBlockDownloadProgress(
            long downloadedBytes,
            long totalBytes) {
        this.downloadedBytes = downloadedBytes;
        this.totalBytes = totalBytes;
    }

    public long getDownloadedBytes() {
        return downloadedBytes;
    }

    public long getTotalBytes() {
        return totalBytes;
    }

    @Override
    public String toString() {
        return "AttachmentsBlockDownloadProgress{" +
                "downloadedBytes=" + downloadedBytes +
                "," + "totalBytes=" + totalBytes +
        "}";
    }

}
