// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from registration.djinni

package net.kullo.libkullo.api;

import java.util.concurrent.atomic.AtomicBoolean;

public abstract class Challenge {
    public abstract ChallengeType type();

    public abstract String text();

    private static final class CppProxy extends Challenge
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
        }

        private native void nativeDestroy(long nativeRef);
        public void destroy()
        {
            boolean destroyed = this.destroyed.getAndSet(true);
            if (!destroyed) nativeDestroy(this.nativeRef);
        }
        protected void finalize() throws java.lang.Throwable
        {
            destroy();
            super.finalize();
        }

        @Override
        public ChallengeType type()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_type(this.nativeRef);
        }
        private native ChallengeType native_type(long _nativeRef);

        @Override
        public String text()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_text(this.nativeRef);
        }
        private native String native_text(long _nativeRef);
    }
}
