// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from client.djinni

package net.kullo.libkullo.api;

import android.support.annotation.NonNull;
import android.support.annotation.Nullable;

/** Listener used in Client.addressExistsAsync() */
public abstract class ClientAddressExistsListener {
    public abstract void finished(@NonNull Address address, boolean exists);

    public abstract void error(@NonNull Address address, @NonNull NetworkError error);
}
