// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from client.djinni

package net.kullo.libkullo.api;

import android.support.annotation.NonNull;
import android.support.annotation.Nullable;

/** Listener used in Client.createSessionAsync() */
public abstract class ClientCreateSessionListener {
    public abstract void migrationStarted(@NonNull Address address);

    public abstract void finished(@NonNull Session session);

    public abstract void error(@NonNull Address address, @NonNull LocalError error);
}
