// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from client.djinni

package net.kullo.libkullo.api;

/** Listener used in Client.addressExistsAsync() */
public abstract class ClientAddressExistsListener {
    public abstract void finished(Address address, boolean exists);

    public abstract void error(Address address, NetworkError error);
}
