// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from client.djinni

package net.kullo.libkullo.api;

import android.support.annotation.NonNull;
import android.support.annotation.Nullable;

/** Listener used in Client.generateKeysAsync() */
public abstract class ClientGenerateKeysListener {
    /** Progress of key generation, in percent. */
    public abstract void progress(byte progress);

    /**
     * Called when key generation is done. Use registration to register an
     * account.
     */
    public abstract void finished(@NonNull Registration registration);
}
