// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from client.djinni

package net.kullo.libkullo.api;

import android.support.annotation.NonNull;
import android.support.annotation.Nullable;

/** Listener used in Client.checkCredentialsAsync() */
public abstract class ClientCheckCredentialsListener {
    public abstract void finished(@NonNull Address address, @NonNull MasterKey masterKey, boolean valid);

    /**
     * Network errors except NetworkError.Unauthorized, which is handled
     * by finished()
     */
    public abstract void error(@NonNull Address address, @NonNull NetworkError error);
}
