// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from datetime.djinni

package net.kullo.libkullo.api;

import android.support.annotation.NonNull;
import android.support.annotation.Nullable;

public class DateTimeBase {


    /*package*/ final short year;

    /*package*/ final byte month;

    /*package*/ final byte day;

    /*package*/ final byte hour;

    /*package*/ final byte minute;

    /*package*/ final byte second;

    /*package*/ final short tzOffsetMinutes;

    public DateTimeBase(
            short year,
            byte month,
            byte day,
            byte hour,
            byte minute,
            byte second,
            short tzOffsetMinutes) {
        this.year = year;
        this.month = month;
        this.day = day;
        this.hour = hour;
        this.minute = minute;
        this.second = second;
        this.tzOffsetMinutes = tzOffsetMinutes;
    }

    public short getYear() {
        return year;
    }

    public byte getMonth() {
        return month;
    }

    public byte getDay() {
        return day;
    }

    public byte getHour() {
        return hour;
    }

    public byte getMinute() {
        return minute;
    }

    public byte getSecond() {
        return second;
    }

    public short getTzOffsetMinutes() {
        return tzOffsetMinutes;
    }

    @Override
    public String toString() {
        return "DateTimeBase{" +
                "year=" + year +
                "," + "month=" + month +
                "," + "day=" + day +
                "," + "hour=" + hour +
                "," + "minute=" + minute +
                "," + "second=" + second +
                "," + "tzOffsetMinutes=" + tzOffsetMinutes +
        "}";
    }

}
