// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from drafts.djinni

package net.kullo.libkullo.api;

/** Listener used in DraftAttachments.contentAsync() */
public abstract class DraftAttachmentsContentListener {
    public abstract void finished(long convId, long attId, byte[] content);
}
