// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from drafts.djinni

package net.kullo.libkullo.api;

import android.support.annotation.NonNull;
import android.support.annotation.Nullable;

/** Listener used in DraftAttachments.saveToAsync() */
public abstract class DraftAttachmentsSaveToListener {
    public abstract void finished(long convId, long attId, @NonNull String path);

    public abstract void error(long convId, long attId, @NonNull String path, @NonNull LocalError error);
}
