// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from errors.djinni

package net.kullo.libkullo.api;

import android.support.annotation.NonNull;
import android.support.annotation.Nullable;

public enum LocalError {
    /** File is too big */
    FILETOOBIG,
    /** Couldn't read or write to file */
    FILESYSTEM,
    /** Any other error */
    UNKNOWN,
    ;
}
