// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from log.djinni

package net.kullo.libkullo.api;

import android.support.annotation.NonNull;
import android.support.annotation.Nullable;

public enum LogType {
    NONE,
    DEBUG,
    INFO,
    WARNING,
    ERROR,
    FATAL,
    ;
}
