// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from masterkey.djinni

package net.kullo.libkullo.api;

import android.support.annotation.NonNull;
import android.support.annotation.Nullable;
import java.util.ArrayList;

public class MasterKeyBase {


    /*package*/ final ArrayList<String> blocks;

    public MasterKeyBase(
            @NonNull ArrayList<String> blocks) {
        this.blocks = blocks;
    }

    /** key as 16 blocks of 6 digits each */
    @NonNull
    public ArrayList<String> getBlocks() {
        return blocks;
    }

    @Override
    public String toString() {
        return "MasterKeyBase{" +
                "blocks=" + blocks +
        "}";
    }

}
