// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from messages.djinni

package net.kullo.libkullo.api;

import android.support.annotation.NonNull;
import android.support.annotation.Nullable;

/** Listener used in MessageAttachments.contentAsync() */
public abstract class MessageAttachmentsContentListener {
    public abstract void finished(long msgId, long attId, @NonNull byte[] content);
}
