// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from messages.djinni

package net.kullo.libkullo.api;

import android.support.annotation.NonNull;
import android.support.annotation.Nullable;

public final class MessagesSearchResult {


    /*package*/ final long msgId;

    /*package*/ final long convId;

    /*package*/ final String senderAddress;

    /*package*/ final DateTime dateReceived;

    /*package*/ final String snippet;

    /*package*/ final String boundary;

    public MessagesSearchResult(
            long msgId,
            long convId,
            @NonNull String senderAddress,
            @NonNull DateTime dateReceived,
            @NonNull String snippet,
            @NonNull String boundary) {
        this.msgId = msgId;
        this.convId = convId;
        this.senderAddress = senderAddress;
        this.dateReceived = dateReceived;
        this.snippet = snippet;
        this.boundary = boundary;
    }

    public long getMsgId() {
        return msgId;
    }

    public long getConvId() {
        return convId;
    }

    @NonNull
    public String getSenderAddress() {
        return senderAddress;
    }

    @NonNull
    public DateTime getDateReceived() {
        return dateReceived;
    }

    /**
     * Snippet contains search strings wrapped in "(XYZ)" and "(/XYZ)" where XYZ
     * is a random boundary in the format [a-zA-Z0-9]+ generated in every search
     */
    @NonNull
    public String getSnippet() {
        return snippet;
    }

    @NonNull
    public String getBoundary() {
        return boundary;
    }

    @Override
    public String toString() {
        return "MessagesSearchResult{" +
                "msgId=" + msgId +
                "," + "convId=" + convId +
                "," + "senderAddress=" + senderAddress +
                "," + "dateReceived=" + dateReceived +
                "," + "snippet=" + snippet +
                "," + "boundary=" + boundary +
        "}";
    }

}
