// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from messages.djinni

package net.kullo.libkullo.api;

import java.util.ArrayList;

public abstract class MessagesSearchListener {
    public abstract void finished(ArrayList<MessagesSearchResult> results);
}
