// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from messages.djinni

package net.kullo.libkullo.api;

import android.support.annotation.NonNull;
import android.support.annotation.Nullable;
import java.util.ArrayList;

public abstract class MessagesSearchListener {
    public abstract void finished(@NonNull ArrayList<MessagesSearchResult> results);
}
