// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from push.djinni

package net.kullo.libkullo.api;

public final class PushToken {


    /*package*/ final PushTokenType type;

    /*package*/ final String token;

    /*package*/ final PushTokenEnvironment environment;

    public PushToken(
            PushTokenType type,
            String token,
            PushTokenEnvironment environment) {
        this.type = type;
        this.token = token;
        this.environment = environment;
    }

    public PushTokenType getType() {
        return type;
    }

    /** GCM: the token; APNS: the hex-encoded token */
    public String getToken() {
        return token;
    }

    public PushTokenEnvironment getEnvironment() {
        return environment;
    }

    @Override
    public String toString() {
        return "PushToken{" +
                "type=" + type +
                "," + "token=" + token +
                "," + "environment=" + environment +
        "}";
    }

}
