// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from registration.djinni

package net.kullo.libkullo.api;

import android.support.annotation.NonNull;
import android.support.annotation.Nullable;

/** Listener used in Registration.registerAccountAsync() */
public abstract class RegistrationRegisterAccountListener {
    public abstract void challengeNeeded(@NonNull Address address, @NonNull Challenge challenge);

    public abstract void addressNotAvailable(@NonNull Address address, @NonNull AddressNotAvailableReason reason);

    public abstract void finished(@NonNull Address address, @NonNull MasterKey masterKey);

    public abstract void error(@NonNull Address address, @NonNull NetworkError error);
}
