// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from messages.djinni

package net.kullo.libkullo.api;

import android.support.annotation.NonNull;
import android.support.annotation.Nullable;

public final class SenderPredicate {


    /*package*/ final SearchPredicateOperator predicateOperator;

    /*package*/ final String senderAddress;

    public SenderPredicate(
            @NonNull SearchPredicateOperator predicateOperator,
            @NonNull String senderAddress) {
        this.predicateOperator = predicateOperator;
        this.senderAddress = senderAddress;
    }

    @NonNull
    public SearchPredicateOperator getPredicateOperator() {
        return predicateOperator;
    }

    @NonNull
    public String getSenderAddress() {
        return senderAddress;
    }

    @Override
    public String toString() {
        return "SenderPredicate{" +
                "predicateOperator=" + predicateOperator +
                "," + "senderAddress=" + senderAddress +
        "}";
    }

}
