// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from syncer.djinni

package net.kullo.libkullo.api;

import android.support.annotation.NonNull;
import android.support.annotation.Nullable;
import java.util.HashMap;

/** Encodes a progress update during syncing. Unknown totals are set to 0. */
public final class SyncProgress {


    /*package*/ final SyncPhase phase;

    /*package*/ final long incomingMessagesProcessed;

    /*package*/ final long incomingMessagesTotal;

    /*package*/ final long incomingMessagesNew;

    /*package*/ final long incomingMessagesNewUnread;

    /*package*/ final long incomingMessagesModified;

    /*package*/ final long incomingMessagesDeleted;

    /*package*/ final long incomingAttachmentsDownloadedBytes;

    /*package*/ final long incomingAttachmentsTotalBytes;

    /*package*/ final HashMap<Long, AttachmentsBlockDownloadProgress> incomingAttachments;

    /*package*/ final long outgoingMessagesUploadedBytes;

    /*package*/ final long outgoingMessagesTotalBytes;

    /*package*/ final long runTimeMs;

    public SyncProgress(
            @NonNull SyncPhase phase,
            long incomingMessagesProcessed,
            long incomingMessagesTotal,
            long incomingMessagesNew,
            long incomingMessagesNewUnread,
            long incomingMessagesModified,
            long incomingMessagesDeleted,
            long incomingAttachmentsDownloadedBytes,
            long incomingAttachmentsTotalBytes,
            @NonNull HashMap<Long, AttachmentsBlockDownloadProgress> incomingAttachments,
            long outgoingMessagesUploadedBytes,
            long outgoingMessagesTotalBytes,
            long runTimeMs) {
        this.phase = phase;
        this.incomingMessagesProcessed = incomingMessagesProcessed;
        this.incomingMessagesTotal = incomingMessagesTotal;
        this.incomingMessagesNew = incomingMessagesNew;
        this.incomingMessagesNewUnread = incomingMessagesNewUnread;
        this.incomingMessagesModified = incomingMessagesModified;
        this.incomingMessagesDeleted = incomingMessagesDeleted;
        this.incomingAttachmentsDownloadedBytes = incomingAttachmentsDownloadedBytes;
        this.incomingAttachmentsTotalBytes = incomingAttachmentsTotalBytes;
        this.incomingAttachments = incomingAttachments;
        this.outgoingMessagesUploadedBytes = outgoingMessagesUploadedBytes;
        this.outgoingMessagesTotalBytes = outgoingMessagesTotalBytes;
        this.runTimeMs = runTimeMs;
    }

    @NonNull
    public SyncPhase getPhase() {
        return phase;
    }

    /** inbox (unit: messages) */
    public long getIncomingMessagesProcessed() {
        return incomingMessagesProcessed;
    }

    public long getIncomingMessagesTotal() {
        return incomingMessagesTotal;
    }

    public long getIncomingMessagesNew() {
        return incomingMessagesNew;
    }

    public long getIncomingMessagesNewUnread() {
        return incomingMessagesNewUnread;
    }

    public long getIncomingMessagesModified() {
        return incomingMessagesModified;
    }

    public long getIncomingMessagesDeleted() {
        return incomingMessagesDeleted;
    }

    /** incoming attachments (unit: bytes) */
    public long getIncomingAttachmentsDownloadedBytes() {
        return incomingAttachmentsDownloadedBytes;
    }

    public long getIncomingAttachmentsTotalBytes() {
        return incomingAttachmentsTotalBytes;
    }

    @NonNull
    public HashMap<Long, AttachmentsBlockDownloadProgress> getIncomingAttachments() {
        return incomingAttachments;
    }

    /** outgoing messages + attachments (unit: uncompressed bytes) */
    public long getOutgoingMessagesUploadedBytes() {
        return outgoingMessagesUploadedBytes;
    }

    public long getOutgoingMessagesTotalBytes() {
        return outgoingMessagesTotalBytes;
    }

    /** Run time of the current sync (unit: milliseconds) */
    public long getRunTimeMs() {
        return runTimeMs;
    }

    @Override
    public String toString() {
        return "SyncProgress{" +
                "phase=" + phase +
                "," + "incomingMessagesProcessed=" + incomingMessagesProcessed +
                "," + "incomingMessagesTotal=" + incomingMessagesTotal +
                "," + "incomingMessagesNew=" + incomingMessagesNew +
                "," + "incomingMessagesNewUnread=" + incomingMessagesNewUnread +
                "," + "incomingMessagesModified=" + incomingMessagesModified +
                "," + "incomingMessagesDeleted=" + incomingMessagesDeleted +
                "," + "incomingAttachmentsDownloadedBytes=" + incomingAttachmentsDownloadedBytes +
                "," + "incomingAttachmentsTotalBytes=" + incomingAttachmentsTotalBytes +
                "," + "incomingAttachments=" + incomingAttachments +
                "," + "outgoingMessagesUploadedBytes=" + outgoingMessagesUploadedBytes +
                "," + "outgoingMessagesTotalBytes=" + outgoingMessagesTotalBytes +
                "," + "runTimeMs=" + runTimeMs +
        "}";
    }

}
