// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from syncer.djinni

package net.kullo.libkullo.api;

public enum SyncPhase {
    KEYS,
    PROFILE,
    /** Downloading and processing of incoming messages */
    INCOMINGMESSAGES,
    /** Downloading and processing of attachments */
    INCOMINGATTACHMENTS,
    /** Sending messages */
    OUTGOINGMESSAGES,
    ;
}
