// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from taskrunner.djinni

package net.kullo.libkullo.api;

import android.support.annotation.NonNull;
import android.support.annotation.Nullable;
import java.util.concurrent.atomic.AtomicBoolean;

/**
 * A task that libkullo wants to be executed asynchronously. It is passed to
 * TaskRunner.
 */
public abstract class Task {
    /** Must not be called from the UI thread. */
    public abstract void run();

    private static final class CppProxy extends Task
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
        }

        private native void nativeDestroy(long nativeRef);
        public void destroy()
        {
            boolean destroyed = this.destroyed.getAndSet(true);
            if (!destroyed) nativeDestroy(this.nativeRef);
        }
        protected void finalize() throws java.lang.Throwable
        {
            destroy();
            super.finalize();
        }

        @Override
        public void run()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_run(this.nativeRef);
        }
        private native void native_run(long _nativeRef);
    }
}
