// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from usersettings.djinni

package net.kullo.libkullo.api;

import android.support.annotation.NonNull;
import android.support.annotation.Nullable;
import java.util.concurrent.atomic.AtomicBoolean;

/** Settings specific to the local user */
public abstract class UserSettings {
    /** Kullo address (e.g. "john.doe#kullo.net") */
    @NonNull
    public abstract Address address();

    @NonNull
    public abstract MasterKey masterKey();

    /** Real name (e.g. "John Doe"). Defaults to "". */
    @NonNull
    public abstract String name();

    public abstract void setName(@NonNull String name);

    /** Organization (e.g. "Doe Inc."). Defaults to "". */
    @NonNull
    public abstract String organization();

    public abstract void setOrganization(@NonNull String organization);

    /** Message footer (e.g. "42 Doe Ave., Doetown 12345"). Defaults to "". */
    @NonNull
    public abstract String footer();

    public abstract void setFooter(@NonNull String footer);

    /** MIME type of the avatar (e.g. "image/jpeg"). Defaults to "". */
    @NonNull
    public abstract String avatarMimeType();

    public abstract void setAvatarMimeType(@NonNull String mimeType);

    /**
     * Binary contents of the avatar image file of type avatarMimeType.
     * Defaults to a zero-length vector.
     */
    @NonNull
    public abstract byte[] avatar();

    public abstract void setAvatar(@NonNull byte[] avatar);

    /**
     * When to show the next backup reminder. Returns null if no reminder date
     * is set. Defaults to a date in the past.
     */
    @Nullable
    public abstract DateTime nextMasterKeyBackupReminder();

    public abstract void setNextMasterKeyBackupReminder(@Nullable DateTime reminderDate);

    private static final class CppProxy extends UserSettings
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
        }

        private native void nativeDestroy(long nativeRef);
        public void destroy()
        {
            boolean destroyed = this.destroyed.getAndSet(true);
            if (!destroyed) nativeDestroy(this.nativeRef);
        }
        protected void finalize() throws java.lang.Throwable
        {
            destroy();
            super.finalize();
        }

        @Override
        public Address address()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_address(this.nativeRef);
        }
        private native Address native_address(long _nativeRef);

        @Override
        public MasterKey masterKey()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_masterKey(this.nativeRef);
        }
        private native MasterKey native_masterKey(long _nativeRef);

        @Override
        public String name()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_name(this.nativeRef);
        }
        private native String native_name(long _nativeRef);

        @Override
        public void setName(String name)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_setName(this.nativeRef, name);
        }
        private native void native_setName(long _nativeRef, String name);

        @Override
        public String organization()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_organization(this.nativeRef);
        }
        private native String native_organization(long _nativeRef);

        @Override
        public void setOrganization(String organization)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_setOrganization(this.nativeRef, organization);
        }
        private native void native_setOrganization(long _nativeRef, String organization);

        @Override
        public String footer()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_footer(this.nativeRef);
        }
        private native String native_footer(long _nativeRef);

        @Override
        public void setFooter(String footer)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_setFooter(this.nativeRef, footer);
        }
        private native void native_setFooter(long _nativeRef, String footer);

        @Override
        public String avatarMimeType()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_avatarMimeType(this.nativeRef);
        }
        private native String native_avatarMimeType(long _nativeRef);

        @Override
        public void setAvatarMimeType(String mimeType)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_setAvatarMimeType(this.nativeRef, mimeType);
        }
        private native void native_setAvatarMimeType(long _nativeRef, String mimeType);

        @Override
        public byte[] avatar()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_avatar(this.nativeRef);
        }
        private native byte[] native_avatar(long _nativeRef);

        @Override
        public void setAvatar(byte[] avatar)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_setAvatar(this.nativeRef, avatar);
        }
        private native void native_setAvatar(long _nativeRef, byte[] avatar);

        @Override
        public DateTime nextMasterKeyBackupReminder()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_nextMasterKeyBackupReminder(this.nativeRef);
        }
        private native DateTime native_nextMasterKeyBackupReminder(long _nativeRef);

        @Override
        public void setNextMasterKeyBackupReminder(DateTime reminderDate)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_setNextMasterKeyBackupReminder(this.nativeRef, reminderDate);
        }
        private native void native_setNextMasterKeyBackupReminder(long _nativeRef, DateTime reminderDate);
    }
}
